from __future__ import annotations

from decimal import Decimal, ROUND_DOWN, ROUND_HALF_UP

SCHEMA_VERSION = "1.0"
DEFAULT_SCHEMA_VERSION = SCHEMA_VERSION
SUPPORTED_SCHEMA_VERSIONS = ("1.0",)

DECIMAL_PRECISION = 28
AMOUNT_QUANTIZER = Decimal("1")
RATE_QUANTIZER = Decimal("0.01")
AMOUNT_ROUNDING = ROUND_DOWN
RATE_ROUNDING = ROUND_HALF_UP

SORT_ASC = "asc"
SORT_DESC = "desc"
VALID_SORT_ORDERS = (SORT_ASC, SORT_DESC)

SELL_REASON_PROFIT_PRESERVE = "profit_preserve"
SELL_REASON_STOP_LOSS = "stop_loss"
SELL_REASON_NO_TRADE = "no_trade"
SELL_REASON_ERROR_SKIP = "error_skip"
SELL_REASON_MISSING_MANDATORY_CANDLE = "missing_mandatory_candle"

NO_TRADE_REASON_CODES = frozenset(
    (
        SELL_REASON_NO_TRADE,
        SELL_REASON_ERROR_SKIP,
        SELL_REASON_MISSING_MANDATORY_CANDLE,
    )
)

SELL_REASON_KO_MAP = {
    SELL_REASON_PROFIT_PRESERVE: "이익보전 매도",
    SELL_REASON_STOP_LOSS: "손절매",
    SELL_REASON_NO_TRADE: "미거래",
    SELL_REASON_ERROR_SKIP: "오류 건너뜀",
    SELL_REASON_MISSING_MANDATORY_CANDLE: "필수 캔들 누락",
}

ERROR_CODES = {
    "E_RP_001": "E-RP-001",
    "E_RP_002": "E-RP-002",
    "E_RP_003": "E-RP-003",
    "E_RP_004": "E-RP-004",
    "E_RP_005": "E-RP-005",
    "E_RP_006": "E-RP-006",
    "E_RP_011": "E-RP-011",
    "E_RP_012": "E-RP-012",
}
