from __future__ import annotations

SYMBOL_PATTERN = r"^[0-9]{6}\.KS$"

DEFAULT_PERIOD = "60d"
DEFAULT_INTERVAL = "5m"
DEFAULT_TIMEOUT_SEC = 10
CACHE_TTL_MIN = 15
DEFAULT_RSI_PERIOD = 14

SUPPORTED_PERIODS = {DEFAULT_PERIOD}
SUPPORTED_INTERVALS = {DEFAULT_INTERVAL}

RETRY_MAX_ATTEMPTS = 3
RETRY_BACKOFF_SECONDS = (1, 2, 4)

MARKETDATA_REQUIRED_COLUMNS = ("open", "high", "low", "close", "volume")
